name: cascade jobs
on: 
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      jobvar: ${{ steps.first.outputs.jobvar }}
    steps:
      - id: first
        run: |
          sleep 20
          echo "jobvar=2500" >> "$GITHUB_OUTPUT"
          echo "Job 1 created"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "this job depends on job 1"
      - run: echo "${{ needs.job1.outputs.jobvar }}"
