name: My hello world job
on:
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: command1
        run: echo "hello world"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List repo files
        run: |
          echo "The repository ${{ github.repository }} contains the files:"
          tree
